namespace TaskFlow.Domain;

public enum OrganizationRole { Owner, Admin, Manager, Member, Viewer }
public enum TaskState { Todo, InProgress, Done }
public sealed class User { public Guid Id { get; set; } = Guid.NewGuid(); public string Email { get; set; } = null!; public string PasswordHash { get; set; } = null!; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public bool IsDisabled { get; set; } }
public sealed class Organization { public Guid Id { get; set; } = Guid.NewGuid(); public string Name { get; set; } = null!; public string TimeZone { get; set; } = "UTC"; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class OrganizationMember { public Guid OrganizationId { get; set; } public Guid UserId { get; set; } public OrganizationRole Role { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class Project { public Guid Id { get; set; } = Guid.NewGuid(); public Guid OrganizationId { get; set; } public string Name { get; set; } = null!; public string? Description { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class TaskItem { public Guid Id { get; set; } = Guid.NewGuid(); public Guid OrganizationId { get; set; } public Guid? ProjectId { get; set; } public Guid CreatedById { get; set; } public Guid? AssigneeId { get; set; } public string Title { get; set; } = null!; public string? Description { get; set; } public TaskState Status { get; set; } public string Priority { get; set; } = "medium"; public DateTimeOffset? DueAt { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; public uint Version { get; set; } }
public sealed class RefreshSession { public Guid Id { get; set; } = Guid.NewGuid(); public Guid UserId { get; set; } public string TokenHash { get; set; } = null!; public DateTimeOffset ExpiresAt { get; set; } public DateTimeOffset? RevokedAt { get; set; } }
public sealed class Subtask { public Guid Id { get; set; } = Guid.NewGuid(); public Guid OrganizationId { get; set; } public Guid TaskId { get; set; } public string Title { get; set; } = null!; public bool IsDone { get; set; } public int SortOrder { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class TaskComment { public Guid Id { get; set; } = Guid.NewGuid(); public Guid OrganizationId { get; set; } public Guid TaskId { get; set; } public Guid AuthorId { get; set; } public string Body { get; set; } = null!; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class Tag { public Guid Id { get; set; } = Guid.NewGuid(); public Guid OrganizationId { get; set; } public string Name { get; set; } = null!; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class TaskTag { public Guid TaskId { get; set; } public Guid TagId { get; set; } public Guid OrganizationId { get; set; } }
