using System.IdentityModel.Tokens.Jwt; using System.Security.Claims; using System.Security.Cryptography; using System.Text; using Microsoft.AspNetCore.Identity; using Microsoft.EntityFrameworkCore; using Microsoft.Extensions.Configuration; using Microsoft.IdentityModel.Tokens; using TaskFlow.Application; using TaskFlow.Domain;
namespace TaskFlow.Infrastructure;
public sealed partial class AuthService(TaskFlowDbContext db, IConfiguration config) : IAuthService {
 readonly PasswordHasher<User> hasher=new();
 [System.Text.RegularExpressions.GeneratedRegex("^[a-zA-Z0-9_]{3,32}$")] private static partial System.Text.RegularExpressions.Regex UsernamePattern();
 public async Task<AuthResult> RegisterAsync(RegisterCommand c,CancellationToken ct){
  var username=c.Username.Trim().ToLowerInvariant();
  if(!UsernamePattern().IsMatch(username))throw new ArgumentException("Username must be 3-32 characters: letters, numbers, and underscores only.");
  if(c.Password.Length<6)throw new ArgumentException("Password must have at least 6 characters.");
  if(await db.Users.AnyAsync(x=>x.Username==username,ct))throw new InvalidOperationException("Username is already taken.");
  var u=new User{Username=username};u.PasswordHash=hasher.HashPassword(u,c.Password);var o=new Organization{Name=c.OrganizationName.Trim()};db.AddRange(u,o,new OrganizationMember{UserId=u.Id,OrganizationId=o.Id,Role=OrganizationRole.Owner});await db.SaveChangesAsync(ct);return await Issue(u,o.Id,ct);
 }
 public async Task<AuthResult?> LoginAsync(LoginCommand c,CancellationToken ct){var u=await db.Users.SingleOrDefaultAsync(x=>x.Username==c.Username.Trim().ToLowerInvariant(),ct);if(u is null||u.IsDisabled||hasher.VerifyHashedPassword(u,u.PasswordHash,c.Password)==PasswordVerificationResult.Failed)return null;var org=await db.Members.Where(x=>x.UserId==u.Id).Select(x=>x.OrganizationId).FirstAsync(ct);return await Issue(u,org,ct);}
 public async Task<AuthResult?> RefreshAsync(string token,CancellationToken ct){var hash=Hash(token);var s=await db.RefreshSessions.SingleOrDefaultAsync(x=>x.TokenHash==hash&&x.RevokedAt==null&&x.ExpiresAt>DateTimeOffset.UtcNow,ct);if(s is null)return null;s.RevokedAt=DateTimeOffset.UtcNow;var org=await db.Members.Where(x=>x.UserId==s.UserId).Select(x=>x.OrganizationId).FirstAsync(ct);return await Issue(await db.Users.FindAsync([s.UserId],ct)??throw new InvalidOperationException(),org,ct);}
 async Task<AuthResult> Issue(User u,Guid org,CancellationToken ct){var expiry=DateTimeOffset.UtcNow.AddMinutes(15);var key=new SymmetricSecurityKey(Encoding.UTF8.GetBytes(config["Jwt:Key"]??throw new InvalidOperationException("JWT key missing")));var jwt=new JwtSecurityToken(claims:[new(JwtRegisteredClaimNames.Sub,u.Id.ToString()),new("org",org.ToString())],expires:expiry.UtcDateTime,signingCredentials:new(key,SecurityAlgorithms.HmacSha256));var refresh=Convert.ToBase64String(RandomNumberGenerator.GetBytes(48));db.RefreshSessions.Add(new(){UserId=u.Id,TokenHash=Hash(refresh),ExpiresAt=DateTimeOffset.UtcNow.AddDays(30)});await db.SaveChangesAsync(ct);return new(new JwtSecurityTokenHandler().WriteToken(jwt),refresh,expiry,org);} static string Hash(string x)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(x)));
}
static class Tenant { public static async Task<bool> IsMember(TaskFlowDbContext d,Guid u,Guid o,CancellationToken c)=>await d.Members.AnyAsync(x=>x.UserId==u&&x.OrganizationId==o,c); public static async Task Require(TaskFlowDbContext d,Guid u,Guid o,CancellationToken c){if(!await IsMember(d,u,o,c))throw new UnauthorizedAccessException();} }
public sealed class TaskService(TaskFlowDbContext db) : ITaskService { static TaskDto D(TaskItem x)=>new(x.Id,x.Title,x.Description,x.Status,x.Priority,x.ProjectId,x.AssigneeId,x.DueAt,x.Version); public async Task<IReadOnlyList<TaskDto>> ListAsync(Guid u,Guid o,CancellationToken c){await Tenant.Require(db,u,o,c);return await db.Tasks.AsNoTracking().Where(x=>x.OrganizationId==o).OrderByDescending(x=>x.UpdatedAt).Select(x=>D(x)).ToListAsync(c);} public async Task<TaskDto> CreateAsync(Guid u,Guid o,CreateTaskCommand c,CancellationToken ct){await Tenant.Require(db,u,o,ct);if(string.IsNullOrWhiteSpace(c.Title)||c.Title.Length>200)throw new ArgumentException("Title is required and must be 200 characters or fewer.");var x=new TaskItem{OrganizationId=o,CreatedById=u,Title=c.Title.Trim(),Description=c.Description?.Trim(),ProjectId=c.ProjectId,AssigneeId=c.AssigneeId,Priority=c.Priority,DueAt=c.DueAt};db.Tasks.Add(x);await db.SaveChangesAsync(ct);return D(x);} public async Task<TaskDto?> UpdateAsync(Guid u,Guid o,Guid id,UpdateTaskCommand c,CancellationToken ct){await Tenant.Require(db,u,o,ct);var x=await db.Tasks.SingleOrDefaultAsync(x=>x.Id==id&&x.OrganizationId==o,ct);if(x is null)return null;if(x.Version!=c.Version)throw new DbUpdateConcurrencyException();x.Title=c.Title.Trim();x.Description=c.Description?.Trim();x.Status=c.Status;x.Priority=c.Priority;x.DueAt=c.DueAt;x.UpdatedAt=DateTimeOffset.UtcNow;x.Version=c.Version+1;await db.SaveChangesAsync(ct);return D(x);} }
public sealed class UserDataService(TaskFlowDbContext db) : IUserDataService {
 static UserDataItem D(UserDataEntry x)=>new(x.Key,x.ValueJson,x.UpdatedAt);
 public async Task<IReadOnlyList<UserDataItem>> ListAsync(Guid u,CancellationToken c)=>await db.UserData.AsNoTracking().Where(x=>x.UserId==u).Select(x=>D(x)).ToListAsync(c);
 public async Task<UserDataItem> UpsertAsync(Guid u,string key,UpsertDataCommand c,CancellationToken ct){
  if(string.IsNullOrWhiteSpace(key)||key.Length>200)throw new ArgumentException("Key is required and must be 200 characters or fewer.");
  var x=await db.UserData.SingleOrDefaultAsync(x=>x.UserId==u&&x.Key==key,ct);
  if(x is null){x=new UserDataEntry{UserId=u,Key=key,ValueJson=c.Value};db.UserData.Add(x);}
  else{x.ValueJson=c.Value;x.UpdatedAt=DateTimeOffset.UtcNow;}
  await db.SaveChangesAsync(ct);
  return D(x);
 }
 public async Task DeleteAsync(Guid u,string key,CancellationToken ct){
  var x=await db.UserData.SingleOrDefaultAsync(x=>x.UserId==u&&x.Key==key,ct);
  if(x is not null){db.UserData.Remove(x);await db.SaveChangesAsync(ct);}
 }
}
public sealed class ProjectService(TaskFlowDbContext db) : IProjectService { static ProjectDto D(Project x)=>new(x.Id,x.Name,x.Description,x.CreatedAt); public async Task<IReadOnlyList<ProjectDto>> ListAsync(Guid u,Guid o,CancellationToken c){await Tenant.Require(db,u,o,c);return await db.Projects.AsNoTracking().Where(x=>x.OrganizationId==o).OrderBy(x=>x.Name).Select(x=>D(x)).ToListAsync(c);} public async Task<ProjectDto> CreateAsync(Guid u,Guid o,CreateProjectCommand c,CancellationToken ct){await Tenant.Require(db,u,o,ct);if(string.IsNullOrWhiteSpace(c.Name)||c.Name.Length>200)throw new ArgumentException("Name is required and must be 200 characters or fewer.");var x=new Project{OrganizationId=o,Name=c.Name.Trim(),Description=c.Description?.Trim()};db.Projects.Add(x);await db.SaveChangesAsync(ct);return D(x);} }
public sealed class SubtaskService(TaskFlowDbContext db) : ISubtaskService {
 static SubtaskDto D(Subtask x)=>new(x.Id,x.TaskId,x.Title,x.IsDone,x.SortOrder);
 static async Task RequireTask(TaskFlowDbContext d,Guid o,Guid taskId,CancellationToken c){if(!await d.Tasks.AnyAsync(x=>x.Id==taskId&&x.OrganizationId==o,c))throw new KeyNotFoundException("Task not found.");}
 public async Task<IReadOnlyList<SubtaskDto>> ListAsync(Guid u,Guid o,Guid taskId,CancellationToken c){await Tenant.Require(db,u,o,c);await RequireTask(db,o,taskId,c);return await db.Subtasks.AsNoTracking().Where(x=>x.OrganizationId==o&&x.TaskId==taskId).OrderBy(x=>x.SortOrder).Select(x=>D(x)).ToListAsync(c);}
 public async Task<SubtaskDto> CreateAsync(Guid u,Guid o,Guid taskId,CreateSubtaskCommand c,CancellationToken ct){await Tenant.Require(db,u,o,ct);await RequireTask(db,o,taskId,ct);if(string.IsNullOrWhiteSpace(c.Title)||c.Title.Length>200)throw new ArgumentException("Title is required and must be 200 characters or fewer.");var count=await db.Subtasks.CountAsync(x=>x.TaskId==taskId,ct);var x=new Subtask{OrganizationId=o,TaskId=taskId,Title=c.Title.Trim(),SortOrder=count};db.Subtasks.Add(x);await db.SaveChangesAsync(ct);return D(x);}
 public async Task<SubtaskDto?> UpdateAsync(Guid u,Guid o,Guid taskId,Guid id,UpdateSubtaskCommand c,CancellationToken ct){await Tenant.Require(db,u,o,ct);var x=await db.Subtasks.SingleOrDefaultAsync(x=>x.Id==id&&x.OrganizationId==o&&x.TaskId==taskId,ct);if(x is null)return null;if(string.IsNullOrWhiteSpace(c.Title)||c.Title.Length>200)throw new ArgumentException("Title is required and must be 200 characters or fewer.");x.Title=c.Title.Trim();x.IsDone=c.IsDone;await db.SaveChangesAsync(ct);return D(x);}
}
public sealed class CommentService(TaskFlowDbContext db) : ICommentService {
 static CommentDto D(TaskComment x)=>new(x.Id,x.TaskId,x.AuthorId,x.Body,x.CreatedAt);
 public async Task<IReadOnlyList<CommentDto>> ListAsync(Guid u,Guid o,Guid taskId,CancellationToken c){await Tenant.Require(db,u,o,c);if(!await db.Tasks.AnyAsync(x=>x.Id==taskId&&x.OrganizationId==o,c))throw new KeyNotFoundException("Task not found.");return await db.TaskComments.AsNoTracking().Where(x=>x.OrganizationId==o&&x.TaskId==taskId).OrderBy(x=>x.CreatedAt).Select(x=>D(x)).ToListAsync(c);}
 public async Task<CommentDto> CreateAsync(Guid u,Guid o,Guid taskId,CreateCommentCommand c,CancellationToken ct){await Tenant.Require(db,u,o,ct);if(!await db.Tasks.AnyAsync(x=>x.Id==taskId&&x.OrganizationId==o,ct))throw new KeyNotFoundException("Task not found.");if(string.IsNullOrWhiteSpace(c.Body)||c.Body.Length>4000)throw new ArgumentException("Comment body is required and must be 4000 characters or fewer.");var x=new TaskComment{OrganizationId=o,TaskId=taskId,AuthorId=u,Body=c.Body.Trim()};db.TaskComments.Add(x);await db.SaveChangesAsync(ct);return D(x);}
}
public sealed class TagService(TaskFlowDbContext db) : ITagService {
 static TagDto D(Tag x)=>new(x.Id,x.Name);
 public async Task<IReadOnlyList<TagDto>> ListAsync(Guid u,Guid o,CancellationToken c){await Tenant.Require(db,u,o,c);return await db.Tags.AsNoTracking().Where(x=>x.OrganizationId==o).OrderBy(x=>x.Name).Select(x=>D(x)).ToListAsync(c);}
 public async Task<TagDto> CreateAsync(Guid u,Guid o,CreateTagCommand c,CancellationToken ct){await Tenant.Require(db,u,o,ct);if(string.IsNullOrWhiteSpace(c.Name)||c.Name.Length>60)throw new ArgumentException("Name is required and must be 60 characters or fewer.");if(await db.Tags.AnyAsync(x=>x.OrganizationId==o&&x.Name==c.Name.Trim(),ct))throw new InvalidOperationException("Tag already exists.");var x=new Tag{OrganizationId=o,Name=c.Name.Trim()};db.Tags.Add(x);await db.SaveChangesAsync(ct);return D(x);}
}
